        !COMPILER-GENERATED INTERFACE MODULE: Thu Apr 02 07:53:33 2009
        MODULE URDCOM_mod
          INTERFACE 
            SUBROUTINE URDCOM(IN,IOUT,LINE)
              INTEGER(KIND=4) :: IN
              INTEGER(KIND=4) :: IOUT
              CHARACTER(*) :: LINE
            END SUBROUTINE URDCOM
          END INTERFACE 
        END MODULE URDCOM_mod
