        !COMPILER-GENERATED INTERFACE MODULE: Thu Apr 02 07:53:34 2009
        MODULE USTOP_mod
          INTERFACE 
            SUBROUTINE USTOP(STOPMESS)
              CHARACTER(*) :: STOPMESS
            END SUBROUTINE USTOP
          END INTERFACE 
        END MODULE USTOP_mod
